# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RoadMap_VK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'PromiseKit'

  # Pods for RoadMap_VK

end
